### ISSUE TITLE
INVALID_ARGUMENT

### ISSUE THREAD

**Issue by pieroashady** [GoogleCloudPlatform/dialogflow-integrations#19]
i got this error:

> Error: 3 INVALID_ARGUMENT: Input text not set.
>     at Object.exports.createStatusError (/srv/node_modules/grpc/src/common.js:91:15)
>     at Object.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:1209:28)
>     at InterceptingListener._callNext (/srv/node_modules/grpc/src/client_interceptors.js:568:42)
>     at InterceptingListener.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:618:8)
>     at callback (/srv/node_modules/grpc/src/client_interceptors.js:847:24)

this error only appear when i send blob via twilio integration. how to fix this?

**Comment by tyhu-google** [comment]
pieroashady@, when you said "send blob", do you mean send blob to twilio or send blob to your integration server?
